### ISSUE TITLE
Codacy Code Cleanup

### ISSUE THREAD

**Issue by skjallargrimmur** [acjim/AcmacsDesktop#115]
The static analysis tool Codacy found some unused code in our project. Please check the project page and fix some of the issues

VIEW HERE: https://www.codacy.com/app/acjim/AcmacsDesktop/dashboard

**Comment by idrissou** [comment]
Hey @skjallargrimmur, 

I had a look at it and mot of the code there is code from functionalities that are on hold, like the HSVtoRGB for coloring nodes,or creating a new map from a map and so on.

I think this is a great tool and a good suggestion we could use towards the end of the project.

**Comment by jidel** [comment]
Well, if the code isn't used, why is it in our main branch?

However, there is no reason why not to include it right now.

**Comment by idrissou** [comment]
@jidel: I would like to remind that few weeks back, when I said I still need the isolate and won't push, you said please push the code even if the functionality is not used.

with your 160 degrees flip flop, I am kind of perplex. This is the second one in one week ( Map controller vs Map ) was the first one.

**Comment by jidel** [comment]
It is **NOT** only your code in the project. If you take a look at the page, it finds issues in all different files. So please, please stop closing this issue.

**Comment by idrissou** [comment]
The code clean up should be done towards the end, because if we remove all unused code right now and close the issue, I am sure there will be more instances where someone may add unused code, and then we will again create a new issue/reopen this issue and start the same process, which is a pure futility and waste of time. 

This is why I told Daniel we should do this once towards the end, though ascertaining the importance of it.

Maybe the issue should not be closed, but it should not be opened as well because it is not pertinent for now.

 As it is a kind of not that clear situation, I closed it and told Daniel to open it later. 

Please stop assuming things and talk to people before assuming anything or taking any decision that goes against their initial decision.

**Comment by rohankoid** [comment]
@idrissou @jidel There is nothing to discuss in this issue, please leave this issue open for @skjallargrimmur since he will be further posting here if he has any questions regarding generic code.

Also @skjallargrimmur there is a functionality on git called git blame, using which you can figure out who does the code belong to (Just incase you didn't know). So if the codacy has very simple problems you can obviously make changes to them but if you have any questions you could check blame and tag particular user to ask your question; if the code is still in progress then user will let you know on the issue itself. Others do not need to interfere on it.

**Comment by rohankoid** [comment]
commit no: d5d1175 induced an error on toolbar item clicks

```[87944:1021/000133:INFO:CONSOLE(12477)] ""ReferenceError: options is not defined\n    at Object.itemClick [as click] (file:///Users/rohan/Documents/workspace/AcmacsDesktop/src/app/components/toolbar/toolbarService.js:121:17)```

**Comment by jidel** [comment]
Closed by accident.
