### ISSUE TITLE
Center map data

### ISSUE THREAD

**Issue by jidel** [acjim/AcmacsDesktop#39]
The scaled map data is not necessarily in the middle of the map svg.
Adjust this by providing initial translate values here: https://github.com/acjim/AcmacsDesktop/blob/master/app/components/map/mapController.js#L80

**Comment by idrissou** [comment]
I Completed this feature by providing two functions. One for the scaled data and another for the non scaled one.
In case we use the raw data, we could call the centerNodesWithoutScaling() function. In case we decide to go with scaled data, we should call centerNodesWithScaling()

**Comment by jidel** [comment]
Then were is the code for it? Please refer to this issue in your commit or in the pull request via `closes #39`

**Comment by idrissou** [comment]
The centerNodesWithoutScaling() function was removed, as well as the saveToJson file one.

Functionality working perfect.

**Comment by jidel** [comment]
Please stop closing issues without referencing in a commit or pull request.
Additionally, there are some bugs when resizing the ng-window. I am working on it right now.

**Comment by jidel** [comment]
Said he and forgot himself... 
Fixed in this commit: https://github.com/acjim/AcmacsDesktop/commit/65d332613bd7f825ea8a2c1e44069d833d35a53a

**Comment by idrissou** [comment]
Hello little twerp,

First, I did not know I had to reference the issue with the commit as we didn't agree on that firsthand.
and by the way yourself you did not reference issue 6 when closing it (Proof=> https://github.com/acjim/AcmacsDesktop/issues/6) so then why the fuck are you giving me a lesson here?

Secondo, If there were some bugs (not in my code) then it is a new issue as it does not have to do anything with the centering the nodes functionality. (you are the one responsible for that part so open an issue for it and fix it without being a pain in the ass)

You know what, I'll tell you straight and stop being politically-correct: you are the main reason I feel not motivated for this project and I knew since you removed Daniel from the FB group that there is something wrong with you mentally.

Hey you know what? I can be a very bad ashole with people like you, so be a man, a respectful one and let us finish this project in peace, otherwise I am afraid you'll see my real me.

Idriss.
